
name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
      
    services:
      datastore-emulator:
        image: emmekappa/google-firestore-emulator
        ports:
        - 8080/tcp
   
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.401
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --logger:"console;verbosity=detailed"
