
name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
      
    services:
      firestore-emulator:
        image: emmekappa/google-firestore-emulator
        ports:
        - 8080/tcp
   
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.401
#    - name: Setup Nuget.exe
#      run: sudo apt-get install nuget
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --logger:"console;verbosity=detailed"
      env:
        FIRESTORE_EMULATOR_HOST: localhost:${{ job.services.firestore-emulator.ports[8080] }}
#    - name: Adding GitHub Package Registry as NuGet Sources
#      run: nuget source Add -Name "GitHub" -Source "https://nuget.pkg.github.com/emmekappa/index.json" -UserName emmekappa -Password ${{ secrets.GITHUB_NUGET_TOKEN }}
#      #-ConfigFile ./nuget.config
    - name: Pack NuGet package
      run: dotnet pack FirestoreSharp
    - name: Publish NuGet package
      run: dotnet nuget push -s "https://nuget.pkg.github.com/emmekappa/index.json" -k ${{ secrets.GITHUB_NUGET_TOKEN }} **/*.nupkg
      
